blog/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='home_page'),

    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('about/', views.about, name='about_page'),

    path('search/', views.search, name='search'),

    path('soobin/', views.soobin, name='soobin'),
    path('yeongjun/', views.yeongjun, name='yeongjun'),
    path('huening_kai/', views.huening_kai, name='huening_kai'),
    path('taehyun/', views.taehyun, name='taehyun'),
    path('beomgyu/', views.beomgyu, name='beomgyu'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from account import views as account_views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),

    path('register/', account_views.register, name='register'),
    path('profile/', account_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(max_length=290, verbose_name='Описание')
    content = models.TextField(verbose_name='Содержание')
    image = models.ImageField(upload_to='news_pics', verbose_name='Изображение', blank=True)
    date = models.DateTimeField(default=timezone.now, verbose_name='Дата')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    @property
    def number_of_comments(self):
        return Comment.objects.filter(post_connected=self).count()

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-date', ]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"


class Comment(models.Model):
    post_connected = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='Содержание')
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.author) + ', ' + self.post_connected.title[:40]

blog/forms.py
from django import forms
from .models import Comment


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.shortcuts import render
from django.db.models import Q
from .models import Post, Comment
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .forms import NewCommentForm


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home_page.html', context)


def about(request):
    return render(request, 'blog/about_page.html')


class PostListView(ListView):
    model = Post
    template_name = 'blog/home_page.html'
    context_object_name = 'posts'
    ordering = ['-date']
    paginate_by = 7


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        comments_connected = Comment.objects.filter(
            post_connected=self.get_object()).order_by('-date_posted')
        data['comments'] = comments_connected
        if self.request.user.is_authenticated:
            data['comment_form'] = NewCommentForm(instance=self.request.user)

        return data

    def post(self, request, *args, **kwargs):
        new_comment = Comment(content=request.POST.get('content',),
        author=self.request.user, post_connected=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'image', 'description']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'image', 'description']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'blog/post_delete.html'
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class SearchView(View):
    def get(self, request, *args, **kwargs):
        queryset = Post.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query)
            ).distinct()
        context = {
            'queryset': queryset
        }
        return render(request, 'blog/search_bar.html', context)


def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query)
        ).distinct()
    context = {
        'queryset': queryset
    }
    return render(request, 'blog/search_bar.html', context)


def soobin(request):
    return render(request, 'artists/soobin.html')


def yeongjun(request):
    return render(request, 'artists/yeongjun.html')


def taehyun(request):
    return render(request, 'artists/taehyun.html')


def beomgyu(request):
    return render(request, 'artists/beomgyu.html')


def huening_kai(request):
    return render(request, 'artists/huening_kai.html')

blog/templates/blog/about_page.html
{% extends 'blog/base.html' %}

{% load static %}


{% block content %}


<style>
figure {
    width:15rem;
    display: grid;
    border-radius: 1rem;
    overflow: hidden;
    cursor: pointer;
}
figure > * {
  grid-area: 1/1;
  transition: .4s;
}
figure figcaption {
  display: grid;
  align-items: end;
  font-family: sans-serif;
  font-size: 2.3rem;
  font-weight: bold;
  color: #0000;
  padding: .75rem;
  background: var(--c,#0009);
  clip-path: inset(0 var(--_i,100%) 0 0);
  -webkit-mask:
    linear-gradient(#000 0 0),
    linear-gradient(#000 0 0);
  -webkit-mask-composite: xor;
  -webkit-mask-clip: text, padding-box;
}
figure:hover figcaption{
  --_i: 0%;
}
figure:hover img {
  transform: scale(1.2);
}
@supports not (-webkit-mask-clip: text) {
  figure figcaption {
   -webkit-mask: none;
   color: #fff;
  }
}
}
body{
      box-sizing: border-box;
}
</style>


<section  class="header1 " style="margin-top:5rem">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-7">
                <div class="right-side">
                    <h5 class="mbr-section-title mbr-fonts-style display-1">
                        <strong>We are <br> Tomorrow x Together</strong>
                    </h5>
                    <p class="mbr-text mbr-fonts-style display-1" style="font-size:30px; margin-top:2rem">
                        TOMORROW X TOGETHER, read as ‘tomorrow by together’, is a bright and youthful boyband aiming to
                        become the next global breakthrough artist.
                        The band is composed of five members, SOOBIN, YEONJUN, BEOMGYU, TAEHYUN, HUENINGKAI,
                        where each member is different from one another, shining in their own way to create synergy.
                    </p>
                </div>
            </div>
            <div class="col-12 col-md-5">
                <img src="{% static 'images/img_3.png' %}" alt="txt"  style=" box-shadow: 40px -42px 0px  rgba(255,255,255, 1);">
            </div>
        </div>
    </div>
</section>


<div style="margin-top:8rem;margin-bottom:10rem">
<div class="col-12 col-md-12 d-flex justify-content-center" >
       <h3>Members</h3>
</div>

<div class="d-flex justify-content-around flex-wrap" style="margin-top:4rem;" >

    <a href="{% url 'blog:soobin' %}" style="text-decoration:none">
        <figure>
            <img src="{% static 'images/soobin.png' %}" alt="Mountains">
            <figcaption>Soobin</figcaption>
        </figure>
   </a>

    <a href="{% url 'blog:yeongjun' %}" style="text-decoration:none">
    <figure>
        <img src="{% static 'images/yeongjun_2.png' %}" alt="Mountains" >
        <figcaption>Yeongjun</figcaption>
    </figure>
    </a>

    <a href="{% url 'blog:taehyun' %}" style="text-decoration:none">
    <figure >
        <img src="{% static 'images/taehyun_2.png' %}" alt="Mountains" >
        <figcaption>Taehyun</figcaption>
    </figure>
    </a>

    <a href="{% url 'blog:beomgyu' %}" style="text-decoration:none">
    <figure >
        <img src="{% static 'images/beomgyu.png' %}" alt="Mountains" >
        <figcaption>Beomgyu</figcaption>
    </figure>
    </a>
    <a href="{% url 'blog:huening_kai' %}" style="text-decoration:none">
    <figure>
        <img src="{% static 'images/huening_kai.png' %}" alt="Mountains" >
        <figcaption>Huening Kai</figcaption>
    </figure>
    </a>

</div>

 </div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js'%}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
          integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">


</head>
<body>
<style>
.header {
  padding: 10px 16px;
  background: #555;
  color: #f1f1f1;
}

.sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

.sticky + .content {
  padding-top: 102px;
}
.button {
   border-radius: 15px;
}
.header {
  width: 100%;
  background: #fff;
  padding: 15px 0;
  z-index: 100;
  -webkit-box-shadow: 0 5px 25px rgba(0, 0, 0, 0.15);
          box-shadow: 0 5px 25px rgba(0, 0, 0, 0.15);
}

.header__inner {
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
      flex-wrap: wrap;
  -webkit-box-pack: justify;
      -ms-flex-pack: justify;
          justify-content: space-between;
  padding: 0 15px;
}

.header_fixed {
  position: fixed;
  left: 0;
  top: 0;
}

body {
  background: #e5ded8;

}
img {
  height: auto;
  max-width: 100%;
  vertical-align: middle;
}

.btn {
  background-color: white;
  border: 1px solid @gray-light;
  //border-radius: 1rem;
  color: @gray-dark;
  padding: 0.5rem;
  text-transform: lowercase;
}


footer {
    position:absolute;
    bottom:auto;
    width:100%;
}

</style>

<header class="py-3 mb-3 border-bottom header" style="background: rgba(245,255,250, 0.9);" id="myHeader">
    <div class="container header__inner">
        <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
            <div class="d-flex align-items-center">
                <a href="{% url 'blog:home_page' %}" class="nav-link px-2 link-secondary"><img
                        src="{% static 'images/logo.png' %}" alt="mdo" width="60" height="60"></a>
                <a href="{% url 'blog:home_page' %}" class="nav-link px-2 link-secondary">Главная</a>
                <a href="{% url 'blog:about_page' %}" class="nav-link px-2 link-dark">О нас</a>
            </div>
            <div class="d-flex justify-content-end align-items-center">
                <form class="w-20 m-3 me-3" action="{% url 'blog:search' %}">
                    <input type="search" class="form-control" placeholder="Поиск..." name="q">
                </form>
                <div class="flex-shrink-0 dropdown">
                    {% if user.is_authenticated %}
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.profile.image.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2" style="">
                        <li><a class="nav-item nav-link" href="{% url 'blog:post-create' %}">Новая запись</a></li>
                        <li><a class="nav-item nav-link" href="{% url 'profile' %}">Профиль</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a></li>
                    </ul>
                    {% else %}
                    <div class="col-md-3 text-end d-flex flex-row">
                        <button type="button" class="btn btn-outline-dark me-2"><a class="nav-item nav-link"
                                                                                   href="{% url 'login' %}">Вход</a>
                        </button>
                        <button type="button" class="btn btn-outline-dark me-2"><a class="nav-item nav-link"
                                                                                   href="{% url 'register' %}">Регистрация</a>
                        </button>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

<div class="wrapper">
<footer class="bg-light text-center text-lg-start content" style="margin-top:5rem;">

    <div class="text-center p-2 d-flex justify-content-around" style="background-color: rgb(255,245,238, 0.9)">
        <div class="d-flex justify-content-between" style="width:10rem">
            <a href="#" style="color:black">
                <i class="bi bi-instagram"></i>
            </a>
            <a href="#" style="color:black">
                <i class="bi bi-facebook"></i>
            </a>
            <a href="#" style="color:black">
                <i class="bi bi-twitter"></i>
            </a>
            <a href="#" style="color:black">
                <i class="bi bi-tiktok"></i>
            </a>
            <a href="#" style="color:black">
                <i class="bi bi-youtube"></i>
            </a>
        </div>
        <div>
            © 2023 Все права защищены:
            <a class="text-dark" href="">Tomorrow X Together</a>
        </div>
    </div>
</footer>
 </div>

<script>
window.onscroll = function() {myFunction()};

var header = document.getElementById("myHeader");
var sticky = header.offsetTop;

function myFunction() {
  if (window.pageYOffset > sticky) {
    header.classList.add("sticky");
  } else {
    header.classList.remove("sticky");
  }
}



</script>
</body>
</html>

blog/templates/blog/home_page.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="" style="">
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/img_9.png' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>TOMORROW X TOGETHER</h5>
        <h1>ACT: SWEET MIRAGE</h1>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/img_8.png' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
      </div>
    </div>
    <div class="carousel-item" style="background-color:rgb(27,35,22)">
      <img src="{% static 'images/img_11.png' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">

      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>



<div style="display:flex; justify-content:space-around; align-items:center; "
     class="row">
    {% for post in posts %}
    <div class="row gx-5 d-flex justify-content-center " style="padding:2rem; margin:1rem; box-shadow: 10px 5px 5px rgb(192,192,192); background-color: rgba(255, 255, 255, 0.25)">
        <div class="col-md-3 mb-6">
            {% if post.image %}
            <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
                <img src="{{ post.image.url }}" style="width:18rem">
            </div>
            {% endif %}
        </div>

        <div class="col-md-8 mb-6">
            <div style="padding: 10px;">
                <img class="rounded-circle article-img" style="width:3rem;" src="{{ post.author.profile.image.url }}">

                <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3">{{ post.author }}</span>
            </div>
            <div style="padding: 25px;">
                <h4><strong>{{ post.title }}</strong></h4>
                <br>
                <p class="text-muted" style="">
                    {{ post.description }}
                </p>
                <small class="text-muted">{{ post.date|date:"F d, Y" }}</small>
                <div style="margin-top:2rem">
                    <a href="{% url 'blog:post-detail' post.id %}" class="btn btn-light">Читать</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


<div class="d-flex justify-content-center  align-items-center" style="margin-top:3rem">
<div class="pagination justify-content-around w-25 align-items-center" >
    {% if is_paginated %}

    {% if page_obj.has_previous %}

    <a class="btn btn-outline-dark mb-4 mr-1" href="?page=1">Первая</a>
    <a class="btn btn-outline-dark mb-4 mr-1" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="btn btn-outline-dark mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a class="btn btn-outline-dark mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-secondary mb-4 mr-1" href="?page={{ page_obj.next_page_number }}">Следующая</a>
    <a class="btn btn-outline-secondary mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
    {% endif %}

    {% endif %}
</div>

</div>
</div>
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Удаление записи</legend>
                <h2>Вы уверены, что хотите удалить эту запись?"{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Да, хочу удалить</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Отмена</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
<!--<article class="media content-section">-->
<!--    <img class="rounded-circle article-img" src="{{ c.author.profile.image.url }}">-->
<!--    <div class="media-body">-->
<!--        <div class="article-metadata">-->
<!--            <a class="mr-2" href="#">{{ object.author }}</a>-->
<!--            <small class="text-muted">{{ object.date|date:"F d, Y" }}</small>-->
<!--            {% if object.author == user %}-->
<!--            <div>-->
<!--                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Редактировать</a>-->
<!--                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Удалить</a>-->
<!--            </div>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--        {% if post.image %}-->
<!--        <div>-->
<!--            <img src="{{ object.image.url }}" style="width:100%;" class="card-img-top">-->
<!--        </div>-->
<!--        {% endif %}-->
<!--        <h2 class="article-title">{{ object.title }}</h2>-->
<!--        <p class="article-content">{{ object.content }}</p>-->
<!--    </div>-->
<!--</article>-->

<div style="display:flex; justify-content:space-around;" class="row">
    {% if object.author == user %}
    <div>
        <a class="btn btn-outline-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}" >Редактировать</a>
        <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Удалить</a>
    </div>
    {% endif %}

    <div class="col-lg-9  mb-5 mb-sm-2">
        {% if post.image %}
        <div class="position-relative image-hover" style="width:25rem;display: block;
    margin-left: auto;
    margin-right: auto">
            <img src="{{ post.image.url }}" class="card-img-top">
            <small class="text-muted">{{ object.date|date:"F d, Y" }}</small>
        </div>
        {% endif %}
        <div style="padding: 10px;">
            <img class="rounded-circle article-img" style="width:3rem;" src="{{ object.author.profile.image.url }}">
            <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3">{{ object.author }}</span>
        </div>
        <h1 class="font-weight-600 mt-3" >
            {{ object.title }}
        </h1>
        <p class="fs-15 font-weight-normal" style="padding:1rem">
            {{ object.content|linebreaks }}
        </p>
    </div>
</div>


<h2>Комментарии</h2>
<div id="comments_section">

  {% if user.is_authenticated %}
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      {{ comment_form|crispy }}
      <button class="btn btn-info" type="submit">Коммент<i class="fas fa-comments"></i></button>
    </div>
  </form>
  {% else %}
    <a class="btn btn-outline-info" href="{% url 'login' %}">Авторизуйтесь</a><br>
  {% endif %}

  {% if comments %}
  <strong class="text-secondary">{{ object.number_of_comments }} Комментариев</strong>
  <hr>
  <ul>
    {% for comment in comments %}
    <li>
     <div>
        <span>
          <strong class="text-info">{{ comment.author }} </strong>
          <small class="text-muted">{{ comment.date_posted }}</small>
        </span>
        <p>
          {{ comment.content|safe }}
        </p>
      </div>
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <strong class="text-secondary">Еще никто ничего не написал...</strong>
  {% endif %}

</div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
{% load crispy_forms_tags %}


<div class="row"
     style="margin:3rem; padding:2rem; background-color:rgb(248,248,255, 0.4); box-shadow: 4px 4px 8px 0px rgba(34, 60, 80, 0.2);">
    <h3 class="border-bottom mb-4">Новая запись</h3>
    <div class="content-section">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <fieldset class="form-group">

                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

blog/templates/blog/search_bar.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<style>
    @import url("https://fonts.googleapis.com/css?family=Raleway:400,400i,700");


.todo {
	width: 100%;
	max-width: 420px;
	background-color: #ddd;
	padding: 2em;
	margin:5rem;
	box-shadow: 1px 2px 4px #0003;
}

h1 {
	margin: 0 auto;
}

ul {
	padding-inline-start: 1.5em;
	font-weight: 400;
}

li {
	position: relative;
	padding-inline-start: 0.5em;
	padding-top: 1.5em;
	border-bottom: 1px solid #48b2;
	cursor: default;
	transition: color 0.4s;

	&::after {
		content: attr(theLittleDetails);
		position: absolute;
		left: 15%; bottom: calc(100% - 1.5em);
		background-image: conic-gradient(from 10deg at 1em 100%, #fff 30deg, #fff0 30deg),
			linear-gradient(0deg, #fff0 1.5em, #fff 1.5em);
		color: #246;
		font-weight: 700;
		padding: 1em 2em 2.5em;
		pointer-events: none;
		opacity: 0;
		filter: drop-shadow(1px 2px 4px #0003);
		transition: opacity 0.4s;
	}

	&:hover {
		color: #48b;

		&::marker {
			font-weight: 700;
		}
		&::after {
			opacity: 1;
			transition-delay: 0.2s;
		}
	}
}


</style>


<div class="d-flex justify-content-center">
    <section class="todo">
        <h1>Todo List</h1>
        This is the results of your search<b> your search</b>
        {% for post in queryset %}
        <ul>
            <li theLittleDetails="Buy at Tom's shop">
				<a href="{{ post.get_absolute_url }}"
                style="text-decoration:none; color:black">{{ post.title }}</a>
				<address style="text-decoration:none; color:blue">{{ post.author }}</address>
            </li>
        </ul>
        {% endfor %}
    </section>
</div>
{% endblock %}